name: offline_rl_shallow_dt
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _py-xgboost-mutex=2.0
  - alsa-lib=1.2.14
  - attr=2.5.1
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cairo=1.18.4
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - contourpy=1.2.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.27
  - dbus=1.13.18
  - expat=2.7.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.55.3
  - freetype=2.13.3
  - future=1.0.0
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - glib=2.84.0
  - glib-tools=2.84.0
  - graphite2=1.3.14
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - gym-notices=0.0.8
  - harfbuzz=11.0.0
  - icu=75.1
  - importlib-metadata=8.6.1
  - importlib_metadata=8.6.1
  - importlib_resources=6.4.0
  - joblib=1.4.2
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libblas=3.9.0
  - libcap=2.75
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.4
  - libclang13=20.1.4
  - libcups=2.3.3
  - libdeflate=1.24
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.4
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.84.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgpg-error=1.55
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.4
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libntlm=1.6
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.5
  - libsndfile=1.2.2
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=257.4
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxgboost=2.1.4
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mpg123=1.32.9
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - nspr=4.36
  - nss=3.111
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.5.0
  - packaging=24.2
  - pandas=2.2.3
  - pcre2=10.44
  - pillow=11.2.1
  - pip=25.1
  - pixman=0.46.0
  - ply=3.11
  - pthread-stubs=0.3
  - pulseaudio-client=17.0
  - py-xgboost=2.1.4
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.9.22
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytz=2025.2
  - pyyaml=6.0.2
  - qt-main=5.15.15
  - readline=8.2
  - scipy=1.13.1
  - seaborn=0.13.2
  - setuptools=75.8.0
  - sip=6.7.12
  - six=1.17.0
  - sqlite=3.49.1
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - tzdata=2025a
  - unicodedata2=15.1.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xgboost=2.1.4
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrender=0.9.12
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.2.2
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cython==0.29.36
      - d4rl==1.1
      - dm-control==1.0.28
      - dm-env==1.6
      - dm-tree==0.1.8
      - ecos==2.0.14
      - etils==1.5.2
      - exceptiongroup==1.3.0
      - fasteners==0.19
      - fsspec==2025.3.2
      - glfw==2.9.0
      - gym==0.23.1
      - h5py==3.13.0
      - idna==3.10
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - jinja2==3.1.6
      - labmaze==1.0.6
      - lxml==5.4.0
      - markupsafe==3.0.2
      - mujoco==3.3.2
      - mujoco-py==2.1.2.14
      - numexpr==2.10.2
      - osqp==1.0.4
      - pluggy==1.6.0
      - protobuf==6.30.2
      - pybullet==3.2.7
      - pycparser==2.22
      - pyopengl==3.1.9
      - pyparsing==3.2.3
      - pystreed==1.3.4
      - pytest==8.3.5
      - requests==2.32.3
      - scikit-learn==1.5.2
      - scikit-survival==0.23.1
      - termcolor==3.0.1
      - typing-extensions==4.13.2
      - urllib3==2.4.0
